default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5
 username: omarhassan
 password: 403102
 host: localhost
 advisory_locks: false
 gssencmode: disable

development:
 <<: *default
 database: family_tree

test:
 <<: *default
 database: family_tree_test

production:
 <<: *default
 database: family_tree_production
 username: postgresql
 password: bJxTunpi09MbZpvgJsYE
 host: family-tree-db.c7kk8sek81rd.eu-central-1.rds.amazonaws.com
 port: 5432
